version: "3"

services:
    database:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1q2w3e4r5t"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        ports:
            - 5432:5432
        volumes:
            - ./source/db:/data/db
        # networks:
        #     - salair.ex
    server:
        container_name: server
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
        environment:
            DATABASE_URL: postgres://postgres:1q2w3e4r5t@database:5432/postgres?sslmode=disable # To be moved to environment file
        ports:
            - 8081:8081
        links:
            - database