version: "3"

services:
    database:
        image: postgres
        container_name: voting_db
        environment:
            POSTGRES_DB: "postgres"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1q2w3e4r5t"
            PGDATA: "/var/lib/postgresql/data/pgdata"
        ports:
            - 5432:5432
        volumes:
            - ./source/db:/data/db
        
    server:
        container_name: voting_app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - database
        ports:
            - 8081:8081
        links:
            - database